### ISSUE TITLE
SVG file with single path won't import

### ISSUE THREAD

**Issue by gumyr** [snoyer/ocpsvg#11]
I have an svg file with a single path in it as follows:
```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->

<svg
   width="210mm"
   height="297mm"
   viewBox="0 0 210 297"
   version="1.1"
   id="svg1634"
   inkscape:version="1.2.2 (732a01da63, 2022-12-09, custom)"
   sodipodi:docname="svg_import_test_wire.svg"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <sodipodi:namedview
     id="namedview1636"
     pagecolor="#ffffff"
     bordercolor="#000000"
     borderopacity="0.25"
     inkscape:showpageshadow="2"
     inkscape:pageopacity="0.0"
     inkscape:pagecheckerboard="0"
     inkscape:deskcolor="#d1d1d1"
     inkscape:document-units="mm"
     showgrid="false"
     inkscape:zoom="0.91100744"
     inkscape:cx="260.15155"
     inkscape:cy="597.68996"
     inkscape:window-width="2490"
     inkscape:window-height="1536"
     inkscape:window-x="0"
     inkscape:window-y="0"
     inkscape:window-maximized="1"
     inkscape:current-layer="layer1" />
  <defs
     id="defs1631" />
  <g
     inkscape:label="Layer 1"
     inkscape:groupmode="layer"
     id="layer1">
    <path
       style="fill:#800000;stroke-width:0.264583"
       d="M 24.281485,56.183336 H 177.76774"
       id="path1640" />
  </g>
</svg>
```
When I try to import this I get the following traceback:
```
Traceback (most recent call last):
  File "/home/roger-maitland/Documents/build123d/import_svg_test.py", line 14, in <module>
    svg = import_svg("svg_import_test_wire.svg")
  File "/home/roger-maitland/Documents/build123d/src/build123d/importers.py", line 234, in import_svg
    for face_or_wire, color_and_label in import_svg_document(
  File "/home/roger-maitland/anaconda3/envs/ocp770/lib/python3.9/site-packages/ocpsvg/svg.py", line 203, in <genexpr>
    for face_or_wire in process_wire(wires, is_filled)
  File "/home/roger-maitland/anaconda3/envs/ocp770/lib/python3.9/site-packages/ocpsvg/svg.py", line 189, in process_wire
    yield from faces_from_wire_soup(wires)
  File "/home/roger-maitland/anaconda3/envs/ocp770/lib/python3.9/site-packages/ocpsvg/ocp.py", line 136, in faces_from_wire_soup
    raise ValueError("wires not coplanar")
ValueError: wires not coplanar
```

**Comment by gumyr** [comment]
Tested with the latest commit - this is still another corner case: when the object is a single straight line (as above) the `are_wires_coplanar` method fails as `BRepLib_FindSurface` doesn't handle this case. This will also likely fail if multiple straight edges are coaxial. In build123d I explicitly cover this case with the following:
```py
        # Are they all co-axial - if so, select one of the infinite planes
        all_edges: list[Edge] = [e for l in all_lines for e in l.edges()]
        if all([e.geom_type() == "LINE" for e in all_edges]):
            as_axis = [Axis(e @ 0, e % 0) for e in all_edges]
            if all([a0.is_coaxial(a1) for a0, a1 in combinations(as_axis, 2)]):
                origin = as_axis[0].position
                x_dir = as_axis[0].direction
                z_dir = as_axis[0].to_plane().x_dir
                c_plane = Plane(origin, z_dir=z_dir)
                result = c_plane.shift_origin((0, 0))
```
don't know if you could do something similar here or just want to say this is an invalid use case.

**Comment by snoyer** [comment]
> This will also likely fail if multiple straight edges are coaxial. In build123d I explicitly cover this case with the following:

I just tried it and I can actually get segfaults in some cases where the coplanar check passes but the wires cannot be made into valid faces (eg. multiple separate non-coaxial segments), fun times.

I'm not going to go as far as you did with the checking yet, but thanks again for the use case, will fix
